// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Support both env names: VITE_SUPABASE_ANON_KEY (preferred) and legacy VITE_SUPABASE_PUBLISHABLE_KEY
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const SUPABASE_ANON_KEY: string | undefined = (import.meta as any).env.VITE_SUPABASE_ANON_KEY || (import.meta as any).env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL) {
  console.error('[Supabase] VITE_SUPABASE_URL is not set. Please add it to your .env');
}
if (!SUPABASE_ANON_KEY) {
  console.error('[Supabase] VITE_SUPABASE_ANON_KEY is not set (or legacy VITE_SUPABASE_PUBLISHABLE_KEY). Please add it to your .env');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});